# Generated by ChatGPT for Siddes Invites scaffold.

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiddesInvite",
            fields=[
                ("id", models.CharField(max_length=96, primary_key=True, serialize=False)),
                ("from_id", models.CharField(max_length=64)),
                ("to_id", models.CharField(max_length=64)),
                ("set_id", models.CharField(max_length=96)),
                ("side", models.CharField(default="friends", max_length=16)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("message", models.CharField(blank=True, default="", max_length=280)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["to_id", "status", "updated_at"], name="inv_to_status_upd"),
                    models.Index(fields=["from_id", "status", "updated_at"], name="inv_from_status_upd"),
                    models.Index(fields=["set_id", "status", "updated_at"], name="inv_set_status_upd"),
                ],
            },
        ),
    ]
