# Generated by ChatGPT for sd_141c (invite set label snapshot).

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siddes_invites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siddesinvite",
            name="set_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
