# Generated by ChatGPT overlay sd_121f (remove deprecated InboxThread.unread_count)

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siddes_inbox", "0002_inboxthreadreadstate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inboxthread",
            name="unread_count",
        ),
    ]
