# Generated by Django 5.2.10 on 2026-01-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siddes_inbox', '0004_remove_inboxthreadreadstate_unread_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxthreadreadstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
