# Generated by Siddes overlay sd_178 (viewer_id per-user read state)

from django.db import migrations, models


def backfill_viewer_id(apps, schema_editor):
    InboxThreadReadState = apps.get_model("siddes_inbox", "InboxThreadReadState")
    for rs in InboxThreadReadState.objects.all():
        if not getattr(rs, "viewer_id", None):
            rs.viewer_id = rs.viewer_role
            rs.save(update_fields=["viewer_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("siddes_inbox", "0005_alter_inboxthreadreadstate_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxthreadreadstate",
            name="viewer_id",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.RunPython(backfill_viewer_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="inboxthreadreadstate",
            name="viewer_id",
            field=models.CharField(max_length=64),
        ),
        migrations.RemoveConstraint(
            model_name="inboxthreadreadstate",
            name="inbox_read_thread_viewer_uniq",
        ),
        migrations.AddConstraint(
            model_name="inboxthreadreadstate",
            constraint=models.UniqueConstraint(
                fields=("thread", "viewer_id"),
                name="inbox_read_thread_viewerid_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="inboxthreadreadstate",
            index=models.Index(fields=["viewer_id", "thread"], name="inbox_read_viewerid_thread"),
        ),
        migrations.AddIndex(
            model_name="inboxthreadreadstate",
            index=models.Index(fields=["thread", "viewer_id"], name="inbox_read_thread_viewerid"),
        ),
    ]
