# Generated by Django 5.2.10 on 2026-01-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siddes_auth', '0007_locality_region_age_gate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountdeletetoken',
            new_name='siddes_auth_user_id_aac7b3_idx',
            old_name='siddes_auth_del_user_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='emailchangetoken',
            new_name='siddes_auth_user_id_1f44de_idx',
            old_name='siddes_auth_emchg_user_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='siddes_auth_user_id_6d0091_idx',
            old_name='siddes_auth_user_id_40d5b7_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='siddes_auth_user_id_284a92_idx',
            old_name='siddes_auth_pwrt_user_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='siddes_auth_user_id_101d2d_idx',
            old_name='siddes_auth_usersess_user_lastseen_idx',
        ),
    ]
