# Generated by Siddes-AI (sd_337)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("siddes_rituals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RitualIgnite",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("by", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.FloatField(db_index=True)),
                (
                    "ritual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ignite_records",
                        to="siddes_rituals.ritual",
                    ),
                ),
            ],
            options={
                "unique_together": {("ritual", "by")},
                "indexes": [
                    models.Index(fields=["ritual", "-created_at"], name="siddes_ritu_ig_rit_4a9c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RitualResponse",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("by", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.FloatField(db_index=True)),
                ("kind", models.CharField(db_index=True, default="", max_length=32)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("text", models.TextField(blank=True, default="")),
                (
                    "ritual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="siddes_rituals.ritual",
                    ),
                ),
            ],
            options={
                "unique_together": {("ritual", "by")},
                "indexes": [
                    models.Index(fields=["ritual", "-created_at"], name="siddes_ritu_rs_rit_0f2b_idx"),
                ],
            },
        ),
    ]
