# Generated by ChatGPT (sd_366): Normalize Set membership.

from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


def _clean_member_id(m: object) -> str | None:
    try:
        s = str(m or '').strip()
    except Exception:
        return None
    if not s:
        return None
    if s.startswith('@'):
        s = '@' + s[1:].strip().lower()
    return s


def forwards(apps, schema_editor):
    SiddesSet = apps.get_model('siddes_sets', 'SiddesSet')
    SiddesSetMember = apps.get_model('siddes_sets', 'SiddesSetMember')

    batch = []
    for s in SiddesSet.objects.all().only('id', 'members'):
        raw = getattr(s, 'members', None)
        if not isinstance(raw, list):
            continue
        seen = set()
        for m in raw:
            mid = _clean_member_id(m)
            if not mid:
                continue
            if mid in seen:
                continue
            seen.add(mid)
            batch.append(SiddesSetMember(set_id=str(s.id), member_id=mid))

        if len(batch) >= 1000:
            SiddesSetMember.objects.bulk_create(batch, ignore_conflicts=True)
            batch = []

    if batch:
        SiddesSetMember.objects.bulk_create(batch, ignore_conflicts=True)


def backwards(apps, schema_editor):
    SiddesSetMember = apps.get_model('siddes_sets', 'SiddesSetMember')
    SiddesSetMember.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('siddes_sets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiddesSetMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='siddes_sets.siddesset')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['member_id'], name='setmem_member'),
                    models.Index(fields=['set', 'member_id'], name='setmem_set_member'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('set', 'member_id'), name='set_member_unique'),
                ],
            },
        ),
        migrations.RunPython(forwards, backwards),
    ]
