# Generated by Siddes apply-helper (sd_741_push_backend_db)
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("viewer_id", models.CharField(db_index=True, max_length=64)),
                ("endpoint", models.TextField(db_index=True)),
                ("p256dh", models.TextField()),
                ("auth", models.TextField()),
                ("raw", models.JSONField(default=dict)),
                ("user_agent", models.CharField(default="", max_length=255)),
                ("created_at", models.FloatField(db_index=True)),
                ("last_seen_at", models.FloatField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("viewer_id", "endpoint")},
                "indexes": [models.Index(fields=["viewer_id", "-created_at"], name="push_viewer_ca")],
            },
        ),
    ]
