# Generated by Siddes apply-helper (sd_743_push_prefs)
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siddes_push", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushPreferences",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("viewer_id", models.CharField(max_length=64, unique=True)),
                ("prefs", models.JSONField(default=dict)),
                ("updated_at", models.FloatField(db_index=True)),
            ],
        ),
    ]
