# Generated by Django 5.2.10 on 2026-01-15 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siddes_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='siddes_post_side_668c52_idx',
            old_name='siddes_post_side_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='siddes_post_author__db8631_idx',
            old_name='siddes_post_author_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='reply',
            new_name='siddes_post_post_id_d50e54_idx',
            old_name='siddes_reply_post_created_at_idx',
        ),
        migrations.AlterField(
            model_name='reply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='siddes_post.post'),
        ),
    ]
