# Generated by Siddes apply-helper (sd_179m)
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siddes_post", "0002_rename_siddes_post_side_created_at_idx_siddes_post_side_668c52_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("post_id", models.CharField(db_index=True, max_length=64)),
                ("viewer_id", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.FloatField(db_index=True)),
            ],
            options={
                "indexes": [models.Index(fields=["post_id", "-created_at"], name="siddes_post_post_i_9d2f6d_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="postlike",
            constraint=models.UniqueConstraint(fields=("post_id", "viewer_id"), name="uniq_post_like_post_viewer"),
        ),
    ]
