# Generated by Django 5.2.10 on 2026-01-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siddes_post', '0003_postlike'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postlike',
            new_name='siddes_post_post_id_a096b2_idx',
            old_name='siddes_post_post_i_9d2f6d_idx',
        ),
    ]
