# Generated by Django 5.2.10 on 2026-01-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siddes_post', '0009_reply_threading'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='siddes_post_echo_of_fe63fc_idx',
            old_name='siddes_post_echoof_created_idx',
        ),
    ]
