# Generated by sd_182_broadcasts_mvp_apply_helper.sh

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                ("id", models.CharField(max_length=96, primary_key=True, serialize=False)),
                ("owner_id", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("handle", models.CharField(db_index=True, max_length=64, unique=True)),
                ("category", models.CharField(default="", max_length=64)),
                ("desc", models.TextField(default="")),
                ("pinned_rules", models.TextField(default="")),
                ("subscriber_count", models.IntegerField(default=0)),
                ("last_post_at", models.FloatField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["subscriber_count", "last_post_at"], name="bc_subs_last"),
                    models.Index(fields=["last_post_at"], name="bc_last_post"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BroadcastMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("viewer_id", models.CharField(db_index=True, max_length=64)),
                ("role", models.CharField(choices=[("owner", "Owner"), ("writer", "Writer"), ("subscriber", "Subscriber")], default="subscriber", max_length=16)),
                ("notify_mode", models.CharField(choices=[("off", "Off"), ("highlights", "Highlights"), ("all", "All")], default="off", max_length=16)),
                ("muted", models.BooleanField(default=False)),
                ("last_seen_at", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "broadcast",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="members", to="siddes_broadcasts.broadcast"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="broadcastmember",
            constraint=models.UniqueConstraint(fields=("broadcast", "viewer_id"), name="bc_member_broadcast_viewer_uniq"),
        ),
        migrations.AddIndex(
            model_name="broadcastmember",
            index=models.Index(fields=["viewer_id", "role"], name="bc_member_viewer_role"),
        ),
        migrations.AddIndex(
            model_name="broadcastmember",
            index=models.Index(fields=["broadcast", "role"], name="bc_member_broadcast_role"),
        ),
    ]
