# Generated by Django 5.2.10 on 2026-01-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siddes_telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telemetryevent',
            name='siddes_tele_viewer__2a3f53_idx',
        ),
        migrations.RemoveField(
            model_name='telemetryevent',
            name='viewer',
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='viewer_id',
            field=models.CharField(default='legacy', max_length=64),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='telemetryevent',
            index=models.Index(fields=['viewer_id', 'event', 'created_at'], name='siddes_tele_viewer__2a3f53_idx'),
        ),
    ]
