# Generated by Siddes overlay (contacts edges) on 2026-01-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("siddes_contacts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMatchEdge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("email", "email"), ("phone", "phone")], default="email", max_length=8)),
                ("domain", models.CharField(blank=True, default="", max_length=128)),
                ("workish", models.BooleanField(default=False)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "matched_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_match_edges_in",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_match_edges_out",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["viewer", "-last_seen_at"], name="sd_ct_edge_v_ls_idx"),
                    models.Index(fields=["matched_user", "-last_seen_at"], name="sd_ct_edge_m_ls_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="contactmatchedge",
            constraint=models.UniqueConstraint(fields=("viewer", "matched_user"), name="sd_ct_edge_uniq_vm"),
        ),
    ]
