# Generated by Siddes apply-helper (sd_181a)
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("viewer_id", models.CharField(db_index=True, max_length=64)),
                ("type", models.CharField(db_index=True, max_length=16)),
                ("actor", models.CharField(default="", max_length=255)),
                ("glimpse", models.TextField(default="")),
                ("post_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("post_title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.FloatField(db_index=True)),
                ("read_at", models.FloatField(blank=True, null=True)),
            ],
            options={
                "indexes": [models.Index(fields=["viewer_id", "-created_at"], name="notif_viewer_ca")],
            },
        ),
    ]
