# Generated by Django 5.2.10 on 2026-01-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siddes_notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='siddes_noti_viewer__86b710_idx',
            old_name='notif_viewer_ca',
        ),
    ]
