# Generated by Django 5.2.10 on 2026-01-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siddes_slate', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='slateentry',
            new_name='siddes_slat_target__a607cd_idx',
            old_name='slate_target_tr_created',
        ),
    ]
